// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwcponjplgtprxwfeqvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3Y3BvbmpwbGd0cHJ4d2ZlcXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDExMzEsImV4cCI6MjA1OTcxNzEzMX0.2u33OXrV7EdxcO_UJ-4o-sSffhwTuM8kI1_BMPNJGA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);